# Generated by Django 3.2.23 on 2024-01-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookquote',
            name='quote_author',
            field=models.CharField(default='', max_length=200),
        ),
    ]
