# Generated by Django 3.2.23 on 2024-01-24 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createbook',
            name='bookmark_book',
            field=models.ManyToManyField(related_name='book_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
