# Generated by Django 3.2.23 on 2024-01-24 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_createbook_bookmark_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createbook',
            name='bookmark_book',
        ),
        migrations.AddField(
            model_name='createbook',
            name='bookmark',
            field=models.ManyToManyField(related_name='book', to=settings.AUTH_USER_MODEL),
        ),
    ]
