# Generated by Django 3.2.23 on 2024-01-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20240124_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createbook',
            old_name='biography',
            new_name='synopsis',
        ),
    ]
