# Generated by Django 3.2.23 on 2024-01-24 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0004_rename_biography_createbook_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbook',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='book', to=settings.AUTH_USER_MODEL),
        ),
    ]
