# Generated by Django 3.2.23 on 2024-01-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_createbook_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='createbook',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
