# Generated by Django 3.2.23 on 2024-01-24 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0005_alter_createbook_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbook',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
