# Generated by Django 3.2.23 on 2024-01-26 10:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_createbook_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbook',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
