# Generated by Django 3.2.23 on 2024-01-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_createbook_image'),
    ]

    operations = [
    ]
